language: c
os: linux
compiler:
    - clang
    - gcc

    apt:
        packages:
            - check
            - valgrind

before_script:
    - ./autogen.sh

script:
    - ./configure && make && make check
