os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        packages:
            - check
            - valgrind
            - clang-3.8
        sources: &sources
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.8

matrix:
    include:
        - env: CC=clang-3.8 ./autogen.sh && make && make check
        - env: CC=gcc ./autogen.sh && make && make check
