compiler:
    - clang
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        packages:
            - check
            - valgrind

script: ./configure && make && make check

matrix:
  include:
    - addons: {apt: {sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.8], packages: [libclang-3.8-dev, clang-3.8]}}
      env: LLVM_VERSION=3.8
      rvm: "2.3.0"
