language: c

dist: trusty

matrix:
    include:
        - compiler: gcc
        - compiler: gcc
          env COMPILER=gcc-5
        - compiler: clang
          env clang=y
        - compiler: clang
          env clang=y COMPILER=clang-3.8
addons:
    apt:
        packages:
            - check
            - valgrind
            - clang-3.8
            - gcc-5
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

before_script:
    - export CC=${COMPILER:-${CC}}
    - ./autogen.sh

script:
    - (./configure && make && make check)
